apiVersion: v1
kind: Service
metadata:
  name: connector
  labels:
    app: connector
    part-of: noui-derp
spec:
  type: ClusterIP
  selector:
    app: connector
  ports:
    - port: {{ .Values.connector.port }}
      targetPort: {{ .Values.connector.port }}
      protocol: TCP
      name: http
