apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    part-of: noui-derp
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
