server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        # Connector endpoints
        location ~ ^/api/v1/members {
            proxy_pass http://connector:8081;
        }
        # Intelligence endpoints
        location ~ ^/api/v1/(eligibility|benefit|dro|composition) {
            proxy_pass http://intelligence:8082;
        }
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
